/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as ProtectedRouteImport } from './routes/_protected/route'
import { Route as IndexImport } from './routes/index'
import { Route as ProtectedProjectsIndexImport } from './routes/_protected/projects/index'
import { Route as ProtectedProjectsProjectIdImport } from './routes/_protected/projects/$projectId'
import { Route as ProtectedProjectsProjectIdEditImport } from './routes/_protected/projects/$projectId.edit'
import { Route as ProtectedProjectsProjectIdIssueCreateImport } from './routes/_protected/projects/$projectId.issue.create'
import { Route as ProtectedProjectsProjectIdIssueIssueIdImport } from './routes/_protected/projects/_.$projectId/issue/$issueId'
import { Route as ProtectedProjectsProjectIdIssueIssueIdEditImport } from './routes/_protected/projects/_.$projectId/issue/_.$issueId.edit'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRouteRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedProjectsIndexRoute = ProtectedProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedProjectsProjectIdRoute = ProtectedProjectsProjectIdImport.update(
  {
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any,
)

const ProtectedProjectsProjectIdEditRoute =
  ProtectedProjectsProjectIdEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ProtectedProjectsProjectIdRoute,
  } as any)

const ProtectedProjectsProjectIdIssueCreateRoute =
  ProtectedProjectsProjectIdIssueCreateImport.update({
    id: '/issue/create',
    path: '/issue/create',
    getParentRoute: () => ProtectedProjectsProjectIdRoute,
  } as any)

const ProtectedProjectsProjectIdIssueIssueIdRoute =
  ProtectedProjectsProjectIdIssueIssueIdImport.update({
    id: '/projects/_/$projectId/issue/$issueId',
    path: '/projects/$projectId/issue/$issueId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

const ProtectedProjectsProjectIdIssueIssueIdEditRoute =
  ProtectedProjectsProjectIdIssueIssueIdEditImport.update({
    id: '/projects/_/$projectId/issue/_/$issueId/edit',
    path: '/projects/$projectId/issue/$issueId/edit',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_protected/projects/$projectId': {
      id: '/_protected/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProtectedProjectsProjectIdImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/projects/': {
      id: '/_protected/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProtectedProjectsIndexImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/projects/$projectId/edit': {
      id: '/_protected/projects/$projectId/edit'
      path: '/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof ProtectedProjectsProjectIdEditImport
      parentRoute: typeof ProtectedProjectsProjectIdImport
    }
    '/_protected/projects/$projectId/issue/create': {
      id: '/_protected/projects/$projectId/issue/create'
      path: '/issue/create'
      fullPath: '/projects/$projectId/issue/create'
      preLoaderRoute: typeof ProtectedProjectsProjectIdIssueCreateImport
      parentRoute: typeof ProtectedProjectsProjectIdImport
    }
    '/_protected/projects/_/$projectId/issue/$issueId': {
      id: '/_protected/projects/_/$projectId/issue/$issueId'
      path: '/projects/$projectId/issue/$issueId'
      fullPath: '/projects/$projectId/issue/$issueId'
      preLoaderRoute: typeof ProtectedProjectsProjectIdIssueIssueIdImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/projects/_/$projectId/issue/_/$issueId/edit': {
      id: '/_protected/projects/_/$projectId/issue/_/$issueId/edit'
      path: '/projects/$projectId/issue/$issueId/edit'
      fullPath: '/projects/$projectId/issue/$issueId/edit'
      preLoaderRoute: typeof ProtectedProjectsProjectIdIssueIssueIdEditImport
      parentRoute: typeof ProtectedRouteImport
    }
  }
}

// Create and export the route tree

interface ProtectedProjectsProjectIdRouteChildren {
  ProtectedProjectsProjectIdEditRoute: typeof ProtectedProjectsProjectIdEditRoute
  ProtectedProjectsProjectIdIssueCreateRoute: typeof ProtectedProjectsProjectIdIssueCreateRoute
}

const ProtectedProjectsProjectIdRouteChildren: ProtectedProjectsProjectIdRouteChildren =
  {
    ProtectedProjectsProjectIdEditRoute: ProtectedProjectsProjectIdEditRoute,
    ProtectedProjectsProjectIdIssueCreateRoute:
      ProtectedProjectsProjectIdIssueCreateRoute,
  }

const ProtectedProjectsProjectIdRouteWithChildren =
  ProtectedProjectsProjectIdRoute._addFileChildren(
    ProtectedProjectsProjectIdRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedProjectsProjectIdRoute: typeof ProtectedProjectsProjectIdRouteWithChildren
  ProtectedProjectsIndexRoute: typeof ProtectedProjectsIndexRoute
  ProtectedProjectsProjectIdIssueIssueIdRoute: typeof ProtectedProjectsProjectIdIssueIssueIdRoute
  ProtectedProjectsProjectIdIssueIssueIdEditRoute: typeof ProtectedProjectsProjectIdIssueIssueIdEditRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedProjectsProjectIdRoute: ProtectedProjectsProjectIdRouteWithChildren,
  ProtectedProjectsIndexRoute: ProtectedProjectsIndexRoute,
  ProtectedProjectsProjectIdIssueIssueIdRoute:
    ProtectedProjectsProjectIdIssueIssueIdRoute,
  ProtectedProjectsProjectIdIssueIssueIdEditRoute:
    ProtectedProjectsProjectIdIssueIssueIdEditRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/projects/$projectId': typeof ProtectedProjectsProjectIdRouteWithChildren
  '/projects': typeof ProtectedProjectsIndexRoute
  '/projects/$projectId/edit': typeof ProtectedProjectsProjectIdEditRoute
  '/projects/$projectId/issue/create': typeof ProtectedProjectsProjectIdIssueCreateRoute
  '/projects/$projectId/issue/$issueId': typeof ProtectedProjectsProjectIdIssueIssueIdRoute
  '/projects/$projectId/issue/$issueId/edit': typeof ProtectedProjectsProjectIdIssueIssueIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/projects/$projectId': typeof ProtectedProjectsProjectIdRouteWithChildren
  '/projects': typeof ProtectedProjectsIndexRoute
  '/projects/$projectId/edit': typeof ProtectedProjectsProjectIdEditRoute
  '/projects/$projectId/issue/create': typeof ProtectedProjectsProjectIdIssueCreateRoute
  '/projects/$projectId/issue/$issueId': typeof ProtectedProjectsProjectIdIssueIssueIdRoute
  '/projects/$projectId/issue/$issueId/edit': typeof ProtectedProjectsProjectIdIssueIssueIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/_protected/projects/$projectId': typeof ProtectedProjectsProjectIdRouteWithChildren
  '/_protected/projects/': typeof ProtectedProjectsIndexRoute
  '/_protected/projects/$projectId/edit': typeof ProtectedProjectsProjectIdEditRoute
  '/_protected/projects/$projectId/issue/create': typeof ProtectedProjectsProjectIdIssueCreateRoute
  '/_protected/projects/_/$projectId/issue/$issueId': typeof ProtectedProjectsProjectIdIssueIssueIdRoute
  '/_protected/projects/_/$projectId/issue/_/$issueId/edit': typeof ProtectedProjectsProjectIdIssueIssueIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/projects/$projectId'
    | '/projects'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/issue/create'
    | '/projects/$projectId/issue/$issueId'
    | '/projects/$projectId/issue/$issueId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/projects/$projectId'
    | '/projects'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/issue/create'
    | '/projects/$projectId/issue/$issueId'
    | '/projects/$projectId/issue/$issueId/edit'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/about'
    | '/_protected/projects/$projectId'
    | '/_protected/projects/'
    | '/_protected/projects/$projectId/edit'
    | '/_protected/projects/$projectId/issue/create'
    | '/_protected/projects/_/$projectId/issue/$issueId'
    | '/_protected/projects/_/$projectId/issue/_/$issueId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_protected",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_protected": {
      "filePath": "_protected/route.tsx",
      "children": [
        "/_protected/projects/$projectId",
        "/_protected/projects/",
        "/_protected/projects/_/$projectId/issue/$issueId",
        "/_protected/projects/_/$projectId/issue/_/$issueId/edit"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_protected/projects/$projectId": {
      "filePath": "_protected/projects/$projectId.tsx",
      "parent": "/_protected",
      "children": [
        "/_protected/projects/$projectId/edit",
        "/_protected/projects/$projectId/issue/create"
      ]
    },
    "/_protected/projects/": {
      "filePath": "_protected/projects/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/projects/$projectId/edit": {
      "filePath": "_protected/projects/$projectId.edit.tsx",
      "parent": "/_protected/projects/$projectId"
    },
    "/_protected/projects/$projectId/issue/create": {
      "filePath": "_protected/projects/$projectId.issue.create.tsx",
      "parent": "/_protected/projects/$projectId"
    },
    "/_protected/projects/_/$projectId/issue/$issueId": {
      "filePath": "_protected/projects/_.$projectId/issue/$issueId.tsx",
      "parent": "/_protected"
    },
    "/_protected/projects/_/$projectId/issue/_/$issueId/edit": {
      "filePath": "_protected/projects/_.$projectId/issue/_.$issueId.edit.tsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
